name: CI
on: [push, pull_request]


jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: ./.github/deployment/deployment.yml
#      - name: Check out repository code
#        uses: actions/checkout@v2
#
#      # Setup Python (faster than using Python container)
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: "3.x"
#
#      - name: Install requirements
#        run: |
#          python -m pip install -r requirements.txt
#      - id: cache-pipenv
#        uses: actions/cache@v1
#        with:
#          path: ~/.local/share/virtualenvs
#          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
#      - name: Run mypy
#        run: |
#            python -m mypy nir_project/generator.py

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: mypy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Run test suite
        run: |
          python -m pytest -v tests/test_generator.py

